apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: production

images:
- name: broadcaster-image
  newName: eplol/broadcaster
  newTag: f6ce72332c7e20e77de7cfa52c13ed147ec4d708
- name: todo-app-image
  newName: eplol/todo-app
  newTag: f6ce72332c7e20e77de7cfa52c13ed147ec4d708
- name: todo-backend-image
  newName: eplol/todo-backend
  newTag: f6ce72332c7e20e77de7cfa52c13ed147ec4d708
