apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: production

images:
- name: broadcaster-image
  newName: eplol/broadcaster
  newTag: 797c974adb710dd0002e4b255862d67f41bfaf35
- name: todo-app-image
  newName: eplol/todo-app
  newTag: 797c974adb710dd0002e4b255862d67f41bfaf35
- name: todo-backend-image
  newName: eplol/todo-backend
  newTag: 797c974adb710dd0002e4b255862d67f41bfaf35
